[package]
name = "fbthrift"
edition = "2018"
version = "0.0.1+unstable"
include = ["src/**/*.rs"]
publish = false

[dependencies]
async-trait = { version = "0.1", features = ["support_old_nightly"] }
bufsize = "0.4"
byteorder = "1.2"
bytes = "0.4"
failure = "0.1"
futures = "0.1"
ghost = "0.1"
num-derive = "0.2"
num-traits = "0.2"
tokio-codec = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"

[dev-dependencies]
quickcheck = "0.6"
tokio = "0.1"
