# @autocargo from //thrift/lib/rust:fbthrift
# Signature<<01b51ad4abd347417e5f1dc0cb6c878d67f71a3e>>
[package]
name = "fbthrift"
edition = "2018"
version = "0.0.1+unstable"
publish = false
include = ["src/**/*.rs"]

[dependencies]
async-trait = { version = "*", features = ["support_old_nightly"] }
bufsize = "*"
byteorder = "*"
bytes = { version="*", features=["serde"] }
failure = "*"
futures = "0.1"
ghost = "*"
num-derive = "*"
num-traits = "*"
tokio-codec = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"

[dev-dependencies]
quickcheck = "0.9"
tokio = "0.1"
# @end of Signature<<01b51ad4abd347417e5f1dc0cb6c878d67f71a3e>>
