# @autocargo from //thrift/lib/rust:fbthrift
# Signature<<ed0c99e953c1039973e5e5a37ad1d9ce3ac3420e>>
[package]
name = "fbthrift"
edition = "2018"
version = "0.0.1+unstable"
publish = false
include = ["src/**/*.rs"]

[dependencies]
anyhow = "*"
async-trait = { version = "*", features = ["support_old_nightly"] }
bufsize = "*"
byteorder = "*"
bytes = { version="*", features=["serde"] }
ghost = "*"
num-derive = "*"
num-traits = "*"
thiserror = "*"

[dev-dependencies]
quickcheck = "0.9"
# @end of Signature<<ed0c99e953c1039973e5e5a37ad1d9ce3ac3420e>>
