# @autocargo from //thrift/lib/rust:fbthrift
# Signature<<58c0f2308c570e18fc09f3d69e71bc333dbf6506>>
[package]
name = "fbthrift"
edition = "2018"
version = "0.0.1+unstable"
publish = false
include = ["src/**/*.rs"]

[dependencies]
async-trait = { version = "*", features = ["support_old_nightly"] }
bufsize = "*"
byteorder = "*"
bytes = { version="*", features=["serde"] }
failure = "*"
ghost = "*"
num-derive = "*"
num-traits = "*"
thiserror = "*"

[dev-dependencies]
quickcheck = "0.9"
# @end of Signature<<58c0f2308c570e18fc09f3d69e71bc333dbf6506>>
